apiVersion: apps/v1
kind: Deployment
metadata:
  name: bec-backend
  labels:
    app: bec-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bec-backend
  template:
    metadata:
      labels:
        app: bec-backend
    spec:
      containers:
      - name: bec-backend
        image: registry.digitalocean.com/bec-registry-2/bec_backend:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "teambec-life-lb"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "969dc671-d381-487d-bef2-6272a7be43df"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: bec-backend
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000 
